import { useEffect, useState } from "react";
import { DEFAULT_PROMPTS } from "../lib/prompts";
import { PROVIDER_DEFAULTS, PROVIDER_LABELS, PROVIDERS, type Provider } from "../lib/providers";
import type { Settings } from "../lib/settings";
import { TEXT_SLOTS, type TextSlot } from "../lib/types";
import { apiGet, apiPost } from "./api";
import { Checkbox } from "./Checkbox";
import { Field } from "./Field";
import { invalidateCatalog, ModelSelect, useCatalog } from "./ModelSelect";
import { missingKeyNames, switchProvider } from "./settings-state";
import { UsageCard } from "./UsageCard";
import {
  buttonPrimaryClasses,
  buttonSecondaryClasses,
  cardClasses,
  cardTitleClasses,
  helperClasses,
  inputClasses,
  labelClasses,
  rowStyle,
  selectClasses,
  stackStyle,
  statusErrorClasses,
  statusIdleClasses,
  textareaClasses,
} from "./ui";

const SLOT_LABELS: Record<TextSlot, string> = {
  title: "Title",
  outline: "Section headings",
  section: "Section content",
  intro: "Introduction",
  outro: "Conclusion",
  faq: "FAQ",
  excerpt: "Excerpt",
  tags: "Tags",
  seo: "SEO meta",
  rewrite: "Rewrite (editor panel)",
  imagePrompt: "Image prompt",
};

type Status = { kind: "idle" | "ok" | "error"; text: string };

export function SettingsPage() {
  const [settings, setSettings] = useState<Settings | null>(null);
  const [status, setStatus] = useState<Status>({ kind: "idle", text: "" });
  const [saving, setSaving] = useState(false);
  const { data: catalog } = useCatalog();

  useEffect(() => {
    void apiGet<{ settings: Settings; defaults: Settings }>("settings").then((r) => {
      if (r.ok === true) setSettings(r.data.settings);
      else setStatus({ kind: "error", text: r.error.message });
    });
  }, []);

  if (!settings) {
    return (
      <p role="status" className={status.kind === "error" ? statusErrorClasses : statusIdleClasses}>
        {status.text || "Loading settings…"}
      </p>
    );
  }

  const set = (patch: Partial<Settings>) => setSettings({ ...settings, ...patch });
  const setModels = (patch: Partial<Settings["models"]>) => set({ models: { ...settings.models, ...patch } });
  const setStepModel = (slot: TextSlot, id: string) =>
    setModels({ steps: { ...settings.models.steps, [slot]: id } });
  const setSlop = (patch: Partial<Settings["noAiSlop"]>) => set({ noAiSlop: { ...settings.noAiSlop, ...patch } });
  const setLinks = (patch: Partial<Settings["internalLinks"]>) =>
    set({ internalLinks: { ...settings.internalLinks, ...patch } });
  const setOverride = (slot: TextSlot, value: string) =>
    set({
      promptOverrides: {
        ...settings.promptOverrides,
        article: { ...settings.promptOverrides.article, [slot]: value },
      },
    });

  const save = async () => {
    setSaving(true);
    const r = await apiPost<{ settings: Settings }>("settings", settings);
    setSaving(false);
    if (r.ok === true) {
      setSettings(r.data.settings);
      invalidateCatalog();
      setStatus({ kind: "ok", text: "Settings saved." });
    } else {
      setStatus({ kind: "error", text: r.error.message });
    }
  };

  const missingKeys = missingKeyNames(settings.providers, catalog ? catalog.keys : null);
  const textProvider = settings.providers.text;
  const imageProvider = settings.providers.image;

  const providerField = (kind: "text" | "image", label: string) => (
    <Field label={label} htmlFor={`aiw-provider-${kind}`}>
      <select
        id={`aiw-provider-${kind}`}
        className={selectClasses}
        value={settings.providers[kind]}
        onChange={(e) => setSettings(switchProvider(settings, kind, e.target.value as Provider))}
      >
        {PROVIDERS.map((p) => (
          <option key={p} value={p}>
            {PROVIDER_LABELS[p]}
          </option>
        ))}
      </select>
    </Field>
  );

  return (
    <div style={stackStyle}>
      <header style={stackStyle}>
        <h2 className={cardTitleClasses}>AI Writer — Settings</h2>
        <p className={helperClasses}>
          Text and images are generated by the providers chosen below. Each step can use its own model; leave a step
          blank to use the default text model.
        </p>
      </header>

      <UsageCard />

      <section className={cardClasses}>
        <div style={stackStyle}>
          <h3 className={cardTitleClasses}>Cost alerts</h3>
          <Field
            label="Warn when OpenRouter credit is below (USD)"
            htmlFor="aiw-low-credit"
            helper="Shown on the dashboard widget and above. 0 turns the warning off."
          >
            <input
              id="aiw-low-credit"
              type="number"
              min={0}
              step={0.5}
              className={inputClasses}
              value={settings.usageAlerts.lowCredit}
              onChange={(e) => set({ usageAlerts: { lowCredit: Math.max(0, Number(e.target.value) || 0) } })}
            />
          </Field>
        </div>
      </section>

      {missingKeys.length > 0 ? (
        <div className={cardClasses} role="alert">
          {missingKeys.map((name) => (
            <p key={name} className={statusErrorClasses}>
              {name} is not bound. Add it to .dev.vars locally or as a Worker secret in production.
            </p>
          ))}
        </div>
      ) : null}

      <section className={cardClasses}>
        <div style={stackStyle}>
          <h3 className={cardTitleClasses}>Models</h3>
          {providerField("text", "Text provider")}
          <Field label="Default text model">
            <ModelSelect
              kind="text"
              provider={textProvider}
              ariaLabel="Default text model"
              value={settings.models.defaultText}
              onChange={(id) => setModels({ defaultText: id })}
              placeholder={`e.g. ${PROVIDER_DEFAULTS[textProvider].defaultText}`}
            />
          </Field>
          <Field label="Fallback text model" helper="Tried once when the chosen text model fails. Leave blank to disable.">
            <ModelSelect
              kind="text"
              provider={textProvider}
              ariaLabel="Fallback text model"
              value={settings.models.fallbackText}
              onChange={(id) => setModels({ fallbackText: id })}
              placeholder="No fallback"
            />
          </Field>
          <details>
            <summary className={labelClasses} style={{ cursor: "pointer" }}>
              Per-step models
            </summary>
            <div style={{ ...stackStyle, marginTop: "1rem" }}>
              {TEXT_SLOTS.map((slot) => (
                <Field key={slot} label={SLOT_LABELS[slot]}>
                  <ModelSelect
                    kind="text"
                    provider={textProvider}
                    ariaLabel={`${SLOT_LABELS[slot]} model`}
                    value={settings.models.steps[slot] ?? ""}
                    onChange={(id) => setStepModel(slot, id)}
                    placeholder={`Default (${settings.models.defaultText})`}
                  />
                </Field>
              ))}
            </div>
          </details>
          {providerField("image", "Image provider")}
          <Field label="Default image model">
            <ModelSelect
              kind="image"
              provider={imageProvider}
              ariaLabel="Default image model"
              value={settings.models.defaultImage}
              onChange={(id) => setModels({ defaultImage: id })}
              placeholder={`e.g. ${PROVIDER_DEFAULTS[imageProvider].defaultImage}`}
            />
          </Field>
        </div>
      </section>

      <section className={cardClasses}>
        <div style={stackStyle}>
          <h3 className={cardTitleClasses}>Generation</h3>
          <div style={rowStyle}>
            <Field label="Image width (px)" htmlFor="aiw-img-w">
              <input
                id="aiw-img-w"
                type="number"
                min={256}
                max={4096}
                className={inputClasses}
                value={settings.imageSize.width}
                onChange={(e) => set({ imageSize: { ...settings.imageSize, width: Number(e.target.value) } })}
              />
            </Field>
            <Field label="Image height (px)" htmlFor="aiw-img-h">
              <input
                id="aiw-img-h"
                type="number"
                min={256}
                max={4096}
                className={inputClasses}
                value={settings.imageSize.height}
                onChange={(e) => set({ imageSize: { ...settings.imageSize, height: Number(e.target.value) } })}
              />
            </Field>
            <Field label="Temperature (0–2)" htmlFor="aiw-temp">
              <input
                id="aiw-temp"
                type="number"
                min={0}
                max={2}
                step={0.1}
                className={inputClasses}
                value={settings.temperature}
                onChange={(e) => set({ temperature: Number(e.target.value) })}
              />
            </Field>
          </div>
          {imageProvider === "minimax" ? (
            <p className={helperClasses}>MiniMax renders 512–2048 px in steps of 8; other sizes are adjusted to fit.</p>
          ) : null}
          <div style={rowStyle}>
            <Field
              label="Fallback language"
              htmlFor="aiw-lang"
              helper="Posts are written in their locale's language (English or Turkish); this is used only when no locale is known."
            >
              <input id="aiw-lang" className={inputClasses} value={settings.language} onChange={(e) => set({ language: e.target.value })} />
            </Field>
            <Field label="Writing style" htmlFor="aiw-style">
              <input id="aiw-style" className={inputClasses} value={settings.style} onChange={(e) => set({ style: e.target.value })} />
            </Field>
            <Field label="Writing tone" htmlFor="aiw-tone">
              <input id="aiw-tone" className={inputClasses} value={settings.tone} onChange={(e) => set({ tone: e.target.value })} />
            </Field>
          </div>
        </div>
      </section>

      <section className={cardClasses}>
        <div style={stackStyle}>
          <h3 className={cardTitleClasses}>No AI slop</h3>
          <p className={helperClasses}>
            New articles are written under the full no-ai-slop rule set (by Peter Yang, MIT): every writing prompt
            carries all of its banned words, empty phrases and patterns. One editing pass then checks each article
            before it is created and fixes anything that slipped through, keeping the meaning, headings and every link
            and never adding claims. Existing posts can be queued from Bulk Edit.
          </p>
          <Checkbox
            label="Write new articles with the no-ai-slop rules"
            checked={settings.noAiSlop.enabled}
            onChange={(enabled) => setSlop({ enabled })}
          />
          <Field label="Editing model" helper="Blank uses the default text model.">
            <ModelSelect
              kind="text"
              provider={textProvider}
              ariaLabel="No AI slop editing model"
              value={settings.noAiSlop.model}
              onChange={(model) => setSlop({ model })}
              placeholder={`Default (${settings.models.defaultText})`}
            />
          </Field>
        </div>
      </section>

      <section className={cardClasses}>
        <div style={stackStyle}>
          <h3 className={cardTitleClasses}>Internal links</h3>
          <p className={helperClasses}>
            When a post is published, AI Writer links phrases in it to related older posts and adds links to it from
            related older posts (existing wording is kept; only phrases become links). Older posts are republished with
            the new link; posts with unpublished editor changes are skipped. Links are added on the next check, within
            15 minutes.
          </p>
          <Checkbox
            label="Add internal links when a post is published"
            checked={settings.internalLinks.enabled}
            onChange={(enabled) => setLinks({ enabled })}
          />
          <div style={rowStyle}>
            <Field label="Links to older posts (max)" htmlFor="aiw-links-out">
              <input
                id="aiw-links-out"
                type="number"
                min={0}
                max={10}
                className={inputClasses}
                value={settings.internalLinks.maxOutbound}
                onChange={(e) => setLinks({ maxOutbound: Number(e.target.value) })}
              />
            </Field>
            <Field label="Older posts linking back (max)" htmlFor="aiw-links-in">
              <input
                id="aiw-links-in"
                type="number"
                min={0}
                max={10}
                className={inputClasses}
                value={settings.internalLinks.maxInbound}
                onChange={(e) => setLinks({ maxInbound: Number(e.target.value) })}
              />
            </Field>
          </div>
          <div style={rowStyle}>
            <Field label="Collections (comma-separated)" htmlFor="aiw-links-collections">
              <input
                id="aiw-links-collections"
                className={inputClasses}
                defaultValue={settings.internalLinks.collections.join(", ")}
                onBlur={(e) =>
                  setLinks({
                    collections: e.target.value
                      .split(",")
                      .map((c) => c.trim())
                      .filter(Boolean),
                  })
                }
              />
            </Field>
            <Field
              label="Link path"
              htmlFor="aiw-links-path"
              helper="{localePrefix} is empty for English and /tr for Turkish; {slug} and {collection} are filled in. The default {localePrefix}/{slug} links to /{slug} and /tr/{slug}. Links always stay within the post's language."
            >
              <input
                id="aiw-links-path"
                className={inputClasses}
                value={settings.internalLinks.pathPattern}
                onChange={(e) => setLinks({ pathPattern: e.target.value })}
              />
            </Field>
          </div>
          <Field label="Linking model" helper="Blank uses the default text model.">
            <ModelSelect
              kind="text"
              provider={textProvider}
              ariaLabel="Internal linking model"
              value={settings.internalLinks.model}
              onChange={(model) => setLinks({ model })}
              placeholder={`Default (${settings.models.defaultText})`}
            />
          </Field>
        </div>
      </section>

      <section className={cardClasses}>
        <div style={stackStyle}>
          <h3 className={cardTitleClasses}>Prompts</h3>
          <Field
            label="Global prompt prefix"
            htmlFor="aiw-prefix"
            helper="Prepended to every text prompt as system instructions (e.g. house style)."
          >
            <textarea
              id="aiw-prefix"
              className={textareaClasses}
              value={settings.promptPrefix}
              onChange={(e) => set({ promptPrefix: e.target.value })}
            />
          </Field>
          <details>
            <summary className={labelClasses} style={{ cursor: "pointer" }}>
              Prompt overrides (article)
            </summary>
            <p className={helperClasses}>
              Variables: %%topic%% %%title%% %%section%% %%sections_count%% %%paragraphs%% %%headings%% %%excerpt%%
              %%existing_tags%% %%language%% %%style%% %%tone%% %%instructions%%. Leave blank to use the default shown.
            </p>
            <div style={{ ...stackStyle, marginTop: "1rem" }}>
              {TEXT_SLOTS.map((slot) => (
                <Field key={slot} label={SLOT_LABELS[slot]} htmlFor={`aiw-prompt-${slot}`}>
                  <textarea
                    id={`aiw-prompt-${slot}`}
                    className={textareaClasses}
                    placeholder={DEFAULT_PROMPTS.article[slot]}
                    value={settings.promptOverrides.article[slot] ?? ""}
                    onChange={(e) => setOverride(slot, e.target.value)}
                  />
                  <div style={rowStyle}>
                    <button type="button" className={buttonSecondaryClasses} onClick={() => setOverride(slot, "")}>
                      Reset to default
                    </button>
                  </div>
                </Field>
              ))}
            </div>
          </details>
        </div>
      </section>

      <div style={rowStyle}>
        <button type="button" className={buttonPrimaryClasses} disabled={saving} onClick={() => void save()}>
          {saving ? "Saving…" : "Save settings"}
        </button>
        {status.text ? (
          <p role="status" className={status.kind === "error" ? statusErrorClasses : statusIdleClasses}>
            {status.text}
          </p>
        ) : null}
      </div>
    </div>
  );
}
