import { defineMiddleware } from "astro:middleware";

import legacyRedirects from "./data/legacy-redirects.json";
import { frontPageSlug } from "./utils/front-page";

/** Paths owned by EmDash or Astro; their routes don't take a trailing slash. */
const SKIPPED_PREFIXES = ["/_emdash", "/_astro", "/_image", "/_server-islands"];
const HAS_EXTENSION = /\/[^/]+\.[a-z0-9]+\/?$/i;
const TRAILING_SLASHES = /\/+$/;

/** Exact WordPress URLs (uploads, attachment pages), generated by scripts/build-legacy-redirects.py. */
const EXACT: Record<string, string> = legacyRedirects;

/**
 * WordPress URL families with no page of their own here, in match order.
 * Each gets the path without its trailing slash and returns the new target.
 */
const RULES: [RegExp, (m: RegExpMatchArray) => string][] = [
	// Admin and login
	[/^\/(wp-admin(\/.*)?|wp-login\.php)$/, () => "/_emdash/admin"],
	// Feeds, including category/tag/comment feeds
	[/^(\/tr)?(\/.*)?\/feed(\/(rss2?|atom|rdf))?$/, (m) => `${m[1] ?? ""}/rss.xml`],
	// Paginated archives
	[/^(\/tr)?\/(category|tag)\/(.+?)\/page\/\d+$/, (m) => `${m[1] ?? ""}/${m[2]}/${m[3]}`],
	[/^(\/tr)?\/page\/\d+$/, (m) => `${m[1] ?? ""}/posts`],
	// Author archives (the byline pages didn't carry over)
	[/^(\/tr)?\/author\/[^/]+(\/.*)?$/, (m) => m[1] ?? "/"],
	// WordPress's default page, deleted in both languages
	[/^(\/tr)?\/sample-page$/, (m) => m[1] ?? "/"],
];

function legacyTarget(path: string): string | undefined {
	const exact = EXACT[path];
	if (exact) return exact;
	for (const [pattern, target] of RULES) {
		const match = path.match(pattern);
		if (match) return target(match);
	}
	return undefined;
}

/**
 * - WordPress-only URLs 301 to their replacement (see RULES and EXACT).
 * - WordPress URLs ended in a slash; EmDash's canonical, sitemap and hreflang
 *   URLs don't. Public `/path/` requests 301 to `/path` so every old URL
 *   consolidates on the one form the site now links to.
 */
export const onRequest = defineMiddleware((context, next) => {
	const { request, url } = context;
	if (request.method !== "GET" && request.method !== "HEAD") return next();

	const { pathname } = url;
	if (pathname === "/") return next();
	if (SKIPPED_PREFIXES.some((prefix) => pathname.startsWith(prefix))) return next();

	const path = pathname.replace(TRAILING_SLASHES, "") || "/";
	const legacy = legacyTarget(path);
	if (legacy) return context.redirect(legacy, 301);

	if (!pathname.endsWith("/") || HAS_EXTENSION.test(pathname)) return next();

	let target = path;
	// A front page's own slug already 301s to its locale home; go there in one hop.
	const segments = target.split("/").slice(1);
	const locale = segments[0] === "tr" ? "tr" : "en";
	const rest = locale === "tr" ? segments.slice(1) : segments;
	if (rest.length === 1 && rest[0] === frontPageSlug(locale)) {
		target = locale === "tr" ? "/tr" : "/";
	}

	return context.redirect(`${target}${url.search}`, 301);
});
